version: '3'

networks:
  postgres-compose-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - postgres-compose-network
    ports:
      - '5434:5432'
    volumes:
      - ''
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  
  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ""
      PGADMIN_DEFAULT_PASSWORD: ""
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network