version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  database:
    container_name: zabbix-database
    image: postgres
    restart: always
    networks:
      - network-zabbix
    ports:
      - '5432:5432'
    volumes:
      - './tmp/database:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix